version: '3.7'
services:
  api:
    build: ./backend
    tty: true
    volumes:
      - ./backend:/go/src/github.com/wasuken/compiew
    ports:
      - "8082:8080"
  front:
    build: ./front
    tty: true
    volumes:
      - ./front:/usr/app
    ports:
      - "3333:3000"
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: compiew
      POSTGRES_PASSWORD: compiew
      POSTGRES_DB: compiew
    ports:
      - 5433:5432
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: ng9
    ports:
      - "7001:8080"
