version: '3.7'
services:
  api:
    build: ./backend
    tty: true
    volumes:
      - ./backend:/go/src/github.com/wasuken/compiew
  front:
    build: ./front
    tty: true
    volumes:
      - ./front:/usr/app
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3333:80"
    depends_on:
      - api
      - front
      - adminer
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: compiew
      POSTGRES_PASSWORD: compiew
      POSTGRES_DB: compiew
  adminer:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: ng9
    depends_on:
      - db
